### ISSUE TITLE
Fix goerli chain ID in /learn/multichain

### ISSUE THREAD

**Issue by Trees0x** [ensdomains/docs-v2#10]
https://alpha-docs.ens.domains/learn/multichain

Goerli ID should be set to 5 in the example code snippet 
<img width="982" alt="Screenshot 2023-07-28 at 12 08 44 PM" src="https://github.com/ensdomains/docs-v2/assets/140471239/65bbba43-56c5-4ae7-9452-181642bd4a17">

**Comment by mrpigg9** [comment]
1
