### ISSUE TITLE
404 EdgeSever error 

### ISSUE THREAD

**Issue by Azizadx** [ensdomains/docs-v2#2]
404 error display when I open link in browser 

![Screenshot 2023-07-25 at 9 58 43 PM](https://github.com/ensdomains/docs-v2/assets/45791956/9884f89c-5899-4389-9628-7a16d2a0d415)

**Comment by lucemans** [comment]
We have moved domains to https://alpha-docs.ens.domains.
Thank you for bringing this up 😊

Closing this for now and will remove any references to the legacy domain!
